runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app

# Optional: Set up environment variables
env_variables:
  SECRET_KEY: "your-secret-key"
  OTHER_ENV_VAR: "value"

# Optional: Static files handler
handlers:
  - url: /static
    static_dir: static

# Optional: Error handlers
error_handlers:
  - file: errors/404.html
    error_code: 404
  - file: errors/500.html
    error_code: 500