runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app

# Optional: Set up environment variables
env_variables:
  SECRET_KEY: "your-secret-key"
  OTHER_ENV_VAR: "value"

# Optional: Static files handler
handlers:
  - url: /static
    static_dir: static

# Error handlers for predefined errors
error_handlers:
  - file: errors/default.html
    error_code: default
  - file: errors/over_quota.html
    error_code: over_quota
  - file: errors/dos_api_denial.html
    error_code: dos_api_denial
  - file: errors/timeout.html
    error_code: timeout